export {default as Green } from './Green-Portal-Sprite.png'
export {default as Purple} from './Purple-Portal-Sprite.png'
export {default as PurpleUpsd} from './Purple-Portal-Sprite-UpsD-1.png'
export {default as GreenRev } from './Green-Portal-Sprite-Rev.png'
export {default as GreenUpsD} from './Green-Portal-Sprite-UpsD.png'