export const LANDING = '/'
export const SIGN_UP = '/signup'
export const LOG_IN = '/login'

export const START = '/play'
export const INTRO = '/intro'
export const ASSEMBLE_BUBOS = '/assemble-bubos'
//export const HINT = '/hint'
export const MAP = '/map'
export const USER = '/user'
//export const TEST = '/test-puzzle'
export const WORMHOLE = '/wormhole'
export const BLOCK_PUZZLE = '/block-puzzle'
export const REFLECTION = '/reflection'
